#!/bin/bash

LUAV=5.1
#LUAV=5.2
#LUAV=5.3

INC=/usr/include/lua"$LUAV"
LIB=-llua"$LUAV"

x() {
  echo "#" "$@"; "$@"
}

x gcc -Wall -Wextra -I"$INC" -I.. -fpic -shared -Os -o objex.so objex.c
x gcc -Wall -Wextra -I"$INC" -I.. -fpic -shared -Os -o flgex.so flgex.c
x gcc -Wall -Wextra -I"$INC" -I.. -fpic -shared -Os -o stkex.so stkex.c
x gcc -Wall -Wextra -I.. -fpic -shared -Os -o sofix.so sofix.c
x gcc -Wall -Wextra -Os -o dlfixex dlfixex.c -ldl
x gcc -Wall -Wextra -I"$INC" -I.. -fpic -shared -Os -o plugin.so plugin.c $LIB -lm -ldl

exit 0

rm -f objex.so flgex.so stkex.so sofix.o sofix.so dlfixex plugin.so
